name: bluebuild
on:
  schedule:
    - cron:
        "00 06 * * *" # build at 06:00 UTC every day
        # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here 
          - recipe-bluefin.yml
          - recipe-bluefin-dx-hwe.yml
        include:
          - recipe: recipe-bluefin.yml
            label-prefix: coreos-stable
            base-image: bluefin-dx
            image-tag: stable
          - recipe: recipe-bluefin-dx-hwe.yml
            label-prefix: bazzite
            base-image: bluefin-dx-hwe
            image-tag: latest
    steps:
      - uses: actions/checkout@v4
      - name: Inspect image and extract label
        run: |
          LABEL_VALUE=${{ matrix.label-prefix }}-$(skopeo inspect docker://ghcr.io/ublue-os/${{ matrix.base-image }}:${{ matrix.image-tag }} | jq -r '"\(.Labels["org.opencontainers.image.version"] | split(".")[0])-\(.Labels["ostree.linux"])"')
          echo "kernel_version=$LABEL_VALUE" >> $GITHUB_ENV
      - name: Display extracted label
        run: |
          echo "Extracted ostree.linux label: $kernel_version"
      - name: Modify file with extracted label
        run: |
          sed -i "s/KERNEL_VERSION/$kernel_version/g" ./recipes/recipe-akmods.yml
       # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          skip_checkout: true

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true
